### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by zbh10** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#11]
where is the demo.py ? thanks!

![image](https://user-images.githubusercontent.com/80090897/198815346-937e2d69-042a-418e-9c2f-8fe354110840.png)

**Comment by Jamie725** [comment]
Sorry that's the guide from Detectron2. I forgot to delete this file. 
Our demo codes are under the demo folder and are separated from FLIR and KASIT datasets.
