### ISSUE TITLE
Training on customer dataset

### ISSUE THREAD

**Issue by bysota** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#14]
Thanks for the excellent work.

In the paper, you said the RGB and T detectors must be trained with the same annoations.
So the two detectors are trained using paired dataset.
How to fusion the detectors trained with different datasets? 
Because we only have own-collected thermal images without RGB ones. 

For paired RGB and T cameras, is there any restrictions for FOV overlapping or resolution?
Thanks.

**Comment by Jamie725** [comment]
Maybe you can split your own dataset to "train" and "validation" datasets and fine-tune detectors on your own dataset?

For the question about paired RGB and T cameras, I am sorry that they didn't give many details on the data they collect. For more information about KAIST and FLIR, please check KAIST paper and FLIR dataset website, thanks
