### ISSUE TITLE
could you release the FLIR annotations you use in your paper?

### ISSUE THREAD

**Issue by x-fish-min** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#2]
## 🚀 Feature
A clear and concise description of the feature proposal.

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers --
we only consider papers that have enough significance and prevalance.

We do not take requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory
contains many of such examples.

**Comment by Jamie725** [comment]
We will release it in the future.

**Comment by sparshgarg23** [comment]
Hi could you provide the link to your paper

**Comment by Jamie725** [comment]
Hi @sparshgarg23,  
I am sorry that I can't at this moment. The paper is under submission right now. I will attach the paper here once there is any update, thanks!

**Comment by heitorrapela** [comment]
@sparshgarg23  https://arxiv.org/pdf/2104.02904.pdf

**Comment by Jamie725** [comment]
Hi @sparshgarg23 and @x-fish-min ,
We just released the annotations files for FLIR! Please check out here: https://drive.google.com/drive/folders/1U1qXYPmts8Xl9xhc1Asb_VpR-_szfNv9?usp=sharing
