### ISSUE TITLE
Significant performance differences between code reproduction and data shown in paper

### ISSUE THREAD

**Issue by fannyzhouha** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#21]
Thanks for your great work, it helped me to gain a deeper understanding of RGBT fusion. But when reprocuding this code, I met some problems, If you could help me, I would be very grateful.  The details are as belows:
Based on demo_ train_ FLIR.py, when reproducing thermal_only, the performance is similar to the data in the paper, but when the methods are changed to early_ fusion and middle_fusion, there is a significant difference between the performance obtained from training and testing compared to the performance given in the paper. What are the possibilities that could lead to this situation? Or what adjustments should be made when reproducing the code?
I only made adjustments to the “method” parameter, the rest are provided by the project code.

**Comment by Jamie725** [comment]
Are you using the NEW FLIR RGB-thermal aligned dataset?
I know that they released a new dataset around 2021 and deleted the unaligned dataset on the internet. Therefore, there could be a performance gap between the two datasets. If you would like to work on the new FLIR dataset, please fine-tune the model with new dataset.
