### ISSUE TITLE
ERROR : No module named evalKAIST

### ISSUE THREAD

**Issue by EdwardDo69** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#22]
Firstly, Thank you for your distribution. 
I am interested in your distribution so I am trying to implement it. When I run “python demo/KAIST/demo_train_KAIST.py”, I get an error “ ModuleNotFoundError: No module named 'evalKAIST' “.
Could you help me fix it?

**Comment by LiYunJamesPhD** [comment]
Hi @EdwardDo69, have you solved the error? I also have the same issue as you while running demo_train_KAIST.py.

Thanks

**Comment by EdwardDo69** [comment]
Unfortunately, I can't solve this problem either.

**Comment by akanuasiegbu** [comment]
I believe this script comes from here
https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/main/evaluation_script/evaluation_script.py

**Comment by Jamie725** [comment]
Sorry, we cleaned and removed all the codes from our server. But if I remember correctly, it is from the link that [akanuasiegbu](https://github.com/akanuasiegbu) provided. Thanks for providing the information here.
