### ISSUE TITLE
How to use pre-trained models for training on new datasets

### ISSUE THREAD

**Issue by LiYunJamesPhD** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#23]
@Jamie725 Thanks for your work. I am trying to run training on my own dataset for comparisons. I would like to know which pre-trained model I should apply to fine-tune the detector models on my dataset. Should I use Detectron2_pretrained_model/model_final_f6e8b1.pkl or KAIST_xxxx_xxx.pth for model fine-tuning?

Thanks,
Li-Yun

**Comment by chenyao1216** [comment]
Hi! @LiYunJamesPhD  have you solved the problem? I also have the same question.

**Comment by LiYunJamesPhD** [comment]
@chenyao1216 I emailed the authors about this issue. According to their response, we should fine-tune Detectron2_pretrained_model/model_final_f6e8b1.pkl on customized datasets; however, I did not really run fine-tuning. Maybe you can try it and let me know how that goes. :)

**Comment by Jamie725** [comment]
Thanks for the questions and sorry for the late reply. 
Yes, you can download the pre-trained models from detectron2: https://github.com/facebookresearch/detectron2/blob/3ff5dd1cff4417af07097064813c9f28d7461d3c/detectron2/model_zoo/model_zoo.py
and fintune to your dataset.
