### ISSUE TITLE
关于代码的一些问题

### ISSUE THREAD

**Issue by medicineqian** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#25]
![image](https://github.com/Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling/assets/74084955/7ad11e43-fcd7-4e5f-81a2-dc881886e16d)
作者你好，我在读detectron2\modeling\meta_arch\rcnn.py这个文件时，发现代码中提取热红外和可见光图片用的是同一个backbone，为什么不是一个用backbone，一个用backbone2呢？
![image](https://github.com/Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling/assets/74084955/04224a32-6935-4a14-878d-70241d05f824)
还有一个问题，关于detectron2\modeling\proposal_generator\build.py文件中所提到的“cfg.MODEL.PROPOSAL_GENERATOR.NAME”参数我在configs\Base-RCNN-FPN.yaml没有找到。

**Comment by Jamie725** [comment]
謝謝您的提問！關於您的問題：
(1)backbone_2：
您的問題很好，我們的設計是希望一個用backbone一個用backbone_2的沒錯，抱歉因為後期我們又做了很多其他的實驗後來沒在main paper上呈現，所以後來整理code release的時候版本有點沒管控好，沒檢查到我上傳的這版本code是使用到同個backbone的，等等會更正，謝謝！
(2) 您可以在這裡找到： https://github.com/facebookresearch/detectron2/blob/3ff5dd1cff4417af07097064813c9f28d7461d3c/detectron2/config/defaults.py#L162
謝謝！
