### ISSUE TITLE
pretrained model require

### ISSUE THREAD

**Issue by xiyufeng2** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#4]
Hello! I want to run the demo 'save_predictions.py' and 'demo_bayesian_fusion.py', but I didn't found the pretrained weights 'out_model_iter_42000.pth'.  Where can I get it?Thanks

**Comment by Jamie725** [comment]
I am still in the process of updating the code base, so I'll upload the pre-trained models once everything is done, thanks

**Comment by Jamie725** [comment]
Hi @xiyufeng2,
I just released the pretrained models. Please check out here: https://drive.google.com/drive/folders/1U1qXYPmts8Xl9xhc1Asb_VpR-_szfNv9?usp=sharing, thanks!
