### ISSUE TITLE
demo_train_middle_fusion ERROR

### ISSUE THREAD

**Issue by xiyufeng2** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#7]
1.When conduct the function:convert_PIL_to_numpy(image, format)  ,ValueError: conversion from L to BGRTTT not supported.
2.trainer.model.backbone_2.weight = param_backbone_2 ,the model has no attribute *backbone_2*.
I heve installed Detectron2 as your instructions,can you tell me what's wrong with it? Thank you.

**Comment by Jamie725** [comment]
It shows that you didn't correctly install the detectron2 with my modification. It seems that it's the original detectron2 released by Meta. Please re-install detectron2 and make sure to follow the instructions provided, thanks
