### ISSUE TITLE
  Could you please provide the predicted files

### ISSUE THREAD

**Issue by 3DMM-ICME2022** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#8]
@Jamie725  Thanks for your nice work.

 Could you please provide the predicted files that contained the bounding box and score of two detectors?
Maybe is the json files in demo_bayesian_fusion.py? If you provided, this project will very clean and easy to follow since we do not need to install the detectors(e.g., Detectron2)

Where is the core codes of ProbEn, such as the Eq(4) and Eq(8), the "bayesian_prior_wt_score_box" in demo_bayesian_fusion.py?

Thanks again for your wonderful paper!

**Comment by XueZ-phd** [comment]
The prediction file on the KAIST dataset is also helpful to me. I hope it will be released.

**Comment by Jamie725** [comment]
Thanks for aksing! We'll release them soon and I'll inform you here once they're released :)

**Comment by XueZ-phd** [comment]
Thanks for your response.

**Comment by kydyahah** [comment]
I hope the prediction file released

**Comment by Jamie725** [comment]
Hi all,
Sorry for the late reply. The results of KAIST have been released here: https://drive.google.com/file/d/1XLjWa2KIrbfjaPGikCjSDIRM9U717Hot/view?usp=sharing , thanks for your patience!
