### ISSUE TITLE
customer dataset

### ISSUE THREAD

**Issue by QinghuanWei** [Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling#9]
Hi, how do I train the model using my own dataset?

**Comment by Jamie725** [comment]
Please refer to this code to register your dataset for training:
https://github.com/Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling/blob/5181301ee1fe30bb058dae6d268770beeb05642f/demo/FLIR/demo_train_FLIR.py#L32
